### ISSUE TITLE
should have pre check before math ?

### ISSUE THREAD

**Issue by piyanggoon** [Pilatuz/bigz#3]
like i said on topic, maybe it should pre check math like 
on sub (u <= v || v == 0) should return zero()

**Comment by Pilatuz** [comment]
no, we are doing wrap-around semantic as standard `uint64` does:

```
var u uint64 = 10
var v uint64 = 20
s := (u - v) // not zero!
```

**Comment by piyanggoon** [comment]
current i use uint256 for calculator like solidity so it possible to add options for pre check for return zero() ?

**Comment by Pilatuz** [comment]
> current i use uint256 for calculator like solidity so it possible to add options for pre check for return zero() ?

no any sense to add this pre-check into library. you can do these checks using existing methods:

```
if u.Cmp(v) <= 0 { // if u <= v
    return uint256.Zero()
}
```
